In [1]:
import gym
import numpy as np

env = gym.make("MountainCar-v0", render_mode=None)
env.reset()

(array([-0.5844998,  0.       ], dtype=float32), {})

In [2]:
env.goal_position

0.5

In [2]:
env.observation_space.high

array([0.6 , 0.07], dtype=float32)

In [5]:
env.observation_space.low[0]

-1.2

In [7]:
buckets_size = 40
discreet_os_size = [buckets_size] * len(env.observation_space.high)
discreet_os_win_size = (env.observation_space.high - env.observation_space.low) / discreet_os_size

obj_end_discreet_state = ((env.goal_position - env.observation_space.low[0]) / discreet_os_win_size[0]).astype(int)
obj_end_discreet_state

37

In [8]:
def get_discreet_state(state):
    discreet_state = (state - env.observation_space.low) / discreet_os_win_size
    return tuple(discreet_state.astype(int))



In [11]:
state = env.reset()
start_discreet = get_discreet_state(state[0])
start_discreet[0]

14

In [4]:
env.action_space.n

3

In [5]:
buckets_size = 20
obs_size = [buckets_size] * len(env.observation_space.high)
obs_size

[20, 20]

In [6]:
discreet_os_win_size = (env.observation_space.high - env.observation_space.low) / obs_size
discreet_os_win_size

array([0.09 , 0.007])

In [7]:
def get_discreet_state(state):
    discreet_state = (state - env.observation_space.low) / discreet_os_win_size
    return tuple(discreet_state.astype(int))

epsilon = 0.95

In [29]:
episodes = 200000
render_per = 1000

learning_rate = 0.1
discount = 0.95 # how important we find future actions

epsilon = 0.95
decay_from = 1000

buckets_size = 20
discreet_os_size = [buckets_size] * len(env.observation_space.high)
discreet_os_win_size = (env.observation_space.high - env.observation_space.low) / discreet_os_size
q_table = np.random.uniform(low=-2, high=0, size=(discreet_os_size + [env.action_space.n]))

In [30]:

done = False

rewards =[]

for episode in range(episodes):
    state = env.reset()
    discreet_state = get_discreet_state(state[0])
    done = False
    episode_reward = 0
    while not done:    
        #if np.random.random() > epsilon:
        action = np.argmax(q_table[discreet_state])
        #else:
            #action = np.random.randint(0, env.action_space.n)
            
        new_state, reward, termination, truncation, _ = env.step(action)
        done = termination or truncation
        episode_reward += reward
        new_discreet_state = get_discreet_state(new_state)
        current_q = q_table[discreet_state + (action,)]    
        if not done:
            max_future_q = np.max(q_table[discreet_state + (action,)])
            new_q = (1 - learning_rate) * current_q + learning_rate * (reward + discount * max_future_q)            
            q_table[discreet_state, (action,)] = new_q
            #print(new_q)
        elif new_state[0] >= env.goal_position:
            q_table[discreet_state + (action, )] = 0
            print(f"I made it on episode {episode}")
    
        discreet_state = new_discreet_state

    rewards.append(episode_reward)

    if episode%render_per == 0:
        print(f"Episode: {episode} Reward:{episode_reward}")


Episode: 0 Reward:-200.0
Episode: 1000 Reward:-200.0
Episode: 2000 Reward:-200.0
Episode: 3000 Reward:-200.0
Episode: 4000 Reward:-200.0
Episode: 5000 Reward:-200.0
Episode: 6000 Reward:-200.0
Episode: 7000 Reward:-200.0
Episode: 8000 Reward:-200.0
Episode: 9000 Reward:-200.0
Episode: 10000 Reward:-200.0
Episode: 11000 Reward:-200.0
Episode: 12000 Reward:-200.0
Episode: 13000 Reward:-200.0
Episode: 14000 Reward:-200.0
Episode: 15000 Reward:-200.0
Episode: 16000 Reward:-200.0
Episode: 17000 Reward:-200.0
Episode: 18000 Reward:-200.0
Episode: 19000 Reward:-200.0
Episode: 20000 Reward:-200.0
Episode: 21000 Reward:-200.0
Episode: 22000 Reward:-200.0
Episode: 23000 Reward:-200.0
Episode: 24000 Reward:-200.0
Episode: 25000 Reward:-200.0
Episode: 26000 Reward:-200.0
Episode: 27000 Reward:-200.0
Episode: 28000 Reward:-200.0
Episode: 29000 Reward:-200.0
Episode: 30000 Reward:-200.0
Episode: 31000 Reward:-200.0
Episode: 32000 Reward:-200.0
Episode: 33000 Reward:-200.0
Episode: 34000 Reward:-200.

In [2]:
state = env.reset()
state

(array([-0.45797673,  0.        ], dtype=float32), {})

In [18]:
env.goal_position


0.5

In [20]:
new_state[0]

-0.6303953

In [29]:
get_discreet_state(new_state)

(7, -70)

In [42]:
discreet_state = (new_state - env.observation_space.low) / discreet_os_win_size
discreet_state

array([17.4152215 , 25.49277608])

In [39]:
new_state - env.observation_space.low

array([0.626948  , 0.07137977], dtype=float32)

In [35]:
env.observation_space.low

array([-1.2 , -0.07], dtype=float32)

In [48]:
env.step(action)

(array([-0.481647  , -0.00550979], dtype=float32), -1.0, False, False, {})